### ISSUE TITLE
colored text

### ISSUE THREAD

**Issue by ashikuri** [fast-average-color/fast-average-color#69]
![image](https://user-images.githubusercontent.com/53426441/113560072-b4a8e280-9602-11eb-8335-9ec3ea9e0486.png)
hello, I want to make like that, but it's not possible with the library

**Comment by hcodes** [comment]
Take the dominant color at the edges of the images. For the text color, use the dominant color of the entire image. You may need to select a color for the color text to have the desired contrast.

**Comment by Oha-you** [comment]
This article might also help: https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/
I still haven't tried it with this library, but it's a good start.

**Comment by Oha-you** [comment]
Also FYI, alternative packages already have functions that pick good-looking text colors:
- https://github.com/Vibrant-Colors/node-vibrant (demo: https://codesandbox.io/s/6zwp7or3wr)
- https://github.com/briangonzalez/jquery.adaptive-backgrounds.js

I think my lazy ass is gonna use `node-vibrant` because I also need some text to be placed on top of the average colored background. And I don't want to spend too much time on it...
