### ISSUE TITLE
Comparison / Benchmarks

### ISSUE THREAD

**Issue by Oha-you** [fast-average-color/fast-average-color#73]
I think every library that claims to be fast needs a proper benchmark or comparison.

Other solutions, sorted by stars:
- https://github.com/lokesh/color-thief
- https://github.com/briangonzalez/jquery.adaptive-backgrounds.js
- https://github.com/Vibrant-Colors/node-vibrant (demo: https://codesandbox.io/s/vibrant-test-iz4x9)
- https://github.com/FormidableLabs/image-palette
- https://github.com/nitin42/react-color-extractor

I kinda like your work the most just by looking at the examples. Thank you and keep it up!

**Comment by hcodes** [comment]
Packages from this list differ, it is incorrect to compare them in terms of speed. This package works faster because it preliminarily reduces the size of the image before calculating it using native browser methods. 

https://fast-average-color.github.io/examples/canvas.html
<img width="491" alt="изображение" src="https://user-images.githubusercontent.com/157520/132102784-04747dff-db9b-45f1-9fc2-e1d32f928ed5.png">
Important! mode: speed, click on other sizes.
